### PR TITLE
2.x - bring versions up-to-date

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@mariuszs Any update on this?

**Comment by mariuszs** [comment]
We need to switch back to pom.xml, because polyglot maven still doesn't support releasing with groovy :(

**Comment by hazendaz** [comment]
I'm good with that.  I personally prefer the pom.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by szpak** [comment]
> We need to switch back to pom.xml, because polyglot maven still doesn't support releasing with groovy :(

@mariuszs Have you reported an issue? Please link it here to make it possible to vote on it or at least to watch to get notified once polyglot Maven will be more production ready.

**Comment by mariuszs** [comment]
ployglot maven is production ready, groovy language in polyglot maven is not

**Comment by szpak** [comment]
@mariuszs I have to believe you. Anyway, can you provide a link to your issue or an existing issue addressing the aforementioned problem? I would like to subscribe on the updates to get know once Groovy can be easily used with polyglot Maven.

**Comment by mariuszs** [comment]
https://github.com/takari/polyglot-maven

> A pom.xml will currently not be installed or deployed except for the Ruby DSL and the Scala DSL but we are working towards this feature for all DSLs.

**Comment by szpak** [comment]
Thanks @mariuszs . Going deeper I have found https://github.com/takari/polyglot-maven/issues/25 and the [last comment](https://github.com/takari/polyglot-maven/issues/25#issuecomment-285740955) from the project contributor mentions:

> Have a look at the README of this project. There you find some info how to use the polyglot-translate-plugin to convert between various dialects including xml. If you use groovy or scala dialect, polyglot-maven automatically installs and deploys a pom.xml in the repository.

Maybe it is an option if we rally would like to use it in production-like projects?

**Pull request merged**
